CREATE DATABASE IF NOT EXISTS meu_pet_sumiu;

USE meu_pet_sumiu;

DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
  id_usuario BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  telefone VARCHAR(15) NOT NULL
);